11:48:53 PersistentVolumeClaim datadir-test-cluster-pxc-0 1767:	waiting for first consumer to be created before binding
11:48:53 PersistentVolumeClaim datadir-test-cluster-pxc-0 1776:	waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
11:48:53 PersistentVolumeClaim datadir-test-cluster-pxc-0 1776:	External provisioner is provisioning volume for claim "acto-namespace/datadir-test-cluster-pxc-0"
11:48:58 PersistentVolumeClaim datadir-test-cluster-pxc-0 1776:	Successfully provisioned volume pvc-8d7dd2cb-4a43-4ebc-a7c2-1ce38e0199ad
11:49:59 PersistentVolumeClaim datadir-test-cluster-pxc-1 2066:	waiting for first consumer to be created before binding
11:49:59 PersistentVolumeClaim datadir-test-cluster-pxc-1 2073:	waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
11:49:59 PersistentVolumeClaim datadir-test-cluster-pxc-1 2073:	External provisioner is provisioning volume for claim "acto-namespace/datadir-test-cluster-pxc-1"
11:50:04 PersistentVolumeClaim datadir-test-cluster-pxc-1 2073:	Successfully provisioned volume pvc-1a1a0432-5d9e-4edf-8561-e8b78eb083b3
11:51:05 PersistentVolumeClaim datadir-test-cluster-pxc-2 2379:	waiting for first consumer to be created before binding
11:51:05 PersistentVolumeClaim datadir-test-cluster-pxc-2 2386:	waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
11:51:05 PersistentVolumeClaim datadir-test-cluster-pxc-2 2386:	External provisioner is provisioning volume for claim "acto-namespace/datadir-test-cluster-pxc-2"
11:51:09 PersistentVolumeClaim datadir-test-cluster-pxc-2 2386:	Successfully provisioned volume pvc-aeb9a0bf-7269-477f-b035-451b148bd370
11:48:53 Pod test-cluster-haproxy-0 1792:	Successfully assigned acto-namespace/test-cluster-haproxy-0 to acto-cluster-6-worker
11:48:54 Pod test-cluster-haproxy-0 1800:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-haproxy" already present on machine
11:48:54 Pod test-cluster-haproxy-0 1800:	Created container haproxy
11:48:54 Pod test-cluster-haproxy-0 1800:	Started container haproxy
11:48:54 Pod test-cluster-haproxy-0 1800:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-haproxy" already present on machine
11:48:54 Pod test-cluster-haproxy-0 1800:	Created container pxc-monit
11:48:54 Pod test-cluster-haproxy-0 1800:	Started container pxc-monit
11:49:13 Pod test-cluster-haproxy-0 1800:	Readiness probe failed: ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 2

11:50:08 Pod test-cluster-haproxy-1 2152:	Successfully assigned acto-namespace/test-cluster-haproxy-1 to acto-cluster-6-worker3
11:50:09 Pod test-cluster-haproxy-1 2154:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-haproxy" already present on machine
11:50:09 Pod test-cluster-haproxy-1 2154:	Created container haproxy
11:50:09 Pod test-cluster-haproxy-1 2154:	Started container haproxy
11:50:09 Pod test-cluster-haproxy-1 2154:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-haproxy" already present on machine
11:50:09 Pod test-cluster-haproxy-1 2154:	Created container pxc-monit
11:50:09 Pod test-cluster-haproxy-1 2154:	Started container pxc-monit
11:50:28 Pod test-cluster-haproxy-2 2239:	Successfully assigned acto-namespace/test-cluster-haproxy-2 to acto-cluster-6-worker2
11:50:29 Pod test-cluster-haproxy-2 2241:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-haproxy" already present on machine
11:50:29 Pod test-cluster-haproxy-2 2241:	Created container haproxy
11:50:29 Pod test-cluster-haproxy-2 2241:	Started container haproxy
11:50:29 Pod test-cluster-haproxy-2 2241:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-haproxy" already present on machine
11:50:29 Pod test-cluster-haproxy-2 2241:	Created container pxc-monit
11:50:30 Pod test-cluster-haproxy-2 2241:	Started container pxc-monit
11:48:53 PodDisruptionBudget test-cluster-haproxy 1793:	No matching pods found
11:48:53 StatefulSet test-cluster-haproxy 1782:	create Pod test-cluster-haproxy-0 in StatefulSet test-cluster-haproxy successful
11:50:08 StatefulSet test-cluster-haproxy 1822:	create Pod test-cluster-haproxy-1 in StatefulSet test-cluster-haproxy successful
11:50:28 StatefulSet test-cluster-haproxy 2155:	create Pod test-cluster-haproxy-2 in StatefulSet test-cluster-haproxy successful
11:48:59 Pod test-cluster-pxc-0 1769:	Successfully assigned acto-namespace/test-cluster-pxc-0 to acto-cluster-6-worker3
11:49:00 Pod test-cluster-pxc-0 1861:	Container image "percona/percona-xtradb-cluster-operator:1.11.0" already present on machine
11:49:00 Pod test-cluster-pxc-0 1861:	Created container pxc-init
11:49:00 Pod test-cluster-pxc-0 1861:	Started container pxc-init
11:49:01 Pod test-cluster-pxc-0 1861:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-logcollector" already present on machine
11:49:01 Pod test-cluster-pxc-0 1861:	Created container logs
11:49:01 Pod test-cluster-pxc-0 1861:	Started container logs
11:49:01 Pod test-cluster-pxc-0 1861:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-logcollector" already present on machine
11:49:01 Pod test-cluster-pxc-0 1861:	Created container logrotate
11:49:02 Pod test-cluster-pxc-0 1861:	Started container logrotate
11:49:02 Pod test-cluster-pxc-0 1861:	Container image "percona/percona-xtradb-cluster:8.0.27-18.1" already present on machine
11:49:02 Pod test-cluster-pxc-0 1861:	Created container pxc
11:49:02 Pod test-cluster-pxc-0 1861:	Started container pxc
11:49:29 Pod test-cluster-pxc-0 1861:	Readiness probe failed: ERROR 2003 (HY000): Can't connect to MySQL server on '10.244.2.4:33062' (111)
+ [[ '' == \P\r\i\m\a\r\y ]]
+ exit 1

11:50:05 Pod test-cluster-pxc-1 2069:	Successfully assigned acto-namespace/test-cluster-pxc-1 to acto-cluster-6-worker2
11:50:06 Pod test-cluster-pxc-1 2116:	Container image "percona/percona-xtradb-cluster-operator:1.11.0" already present on machine
11:50:06 Pod test-cluster-pxc-1 2116:	Created container pxc-init
11:50:06 Pod test-cluster-pxc-1 2116:	Started container pxc-init
11:50:07 Pod test-cluster-pxc-1 2116:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-logcollector" already present on machine
11:50:07 Pod test-cluster-pxc-1 2116:	Created container logs
11:50:08 Pod test-cluster-pxc-1 2116:	Started container logs
11:50:08 Pod test-cluster-pxc-1 2116:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-logcollector" already present on machine
11:50:08 Pod test-cluster-pxc-1 2116:	Created container logrotate
11:50:08 Pod test-cluster-pxc-1 2116:	Started container logrotate
11:50:08 Pod test-cluster-pxc-1 2116:	Container image "percona/percona-xtradb-cluster:8.0.27-18.1" already present on machine
11:50:08 Pod test-cluster-pxc-1 2116:	Created container pxc
11:50:08 Pod test-cluster-pxc-1 2116:	Started container pxc
11:50:35 Pod test-cluster-pxc-1 2116:	Readiness probe failed: ERROR 2003 (HY000): Can't connect to MySQL server on '10.244.3.4:33062' (111)
+ [[ '' == \P\r\i\m\a\r\y ]]
+ exit 1

11:51:10 Pod test-cluster-pxc-2 2382:	Successfully assigned acto-namespace/test-cluster-pxc-2 to acto-cluster-6-worker
11:51:11 Pod test-cluster-pxc-2 2415:	Container image "percona/percona-xtradb-cluster-operator:1.11.0" already present on machine
11:51:11 Pod test-cluster-pxc-2 2415:	Created container pxc-init
11:51:12 Pod test-cluster-pxc-2 2415:	Started container pxc-init
11:51:13 Pod test-cluster-pxc-2 2415:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-logcollector" already present on machine
11:51:13 Pod test-cluster-pxc-2 2415:	Created container logs
11:51:13 Pod test-cluster-pxc-2 2415:	Started container logs
11:51:13 Pod test-cluster-pxc-2 2415:	Container image "percona/percona-xtradb-cluster-operator:1.11.0-logcollector" already present on machine
11:51:13 Pod test-cluster-pxc-2 2415:	Created container logrotate
11:51:13 Pod test-cluster-pxc-2 2415:	Started container logrotate
11:51:13 Pod test-cluster-pxc-2 2415:	Container image "percona/percona-xtradb-cluster:8.0.27-18.1" already present on machine
11:51:13 Pod test-cluster-pxc-2 2415:	Created container pxc
11:51:14 Pod test-cluster-pxc-2 2415:	Started container pxc
11:51:41 Pod test-cluster-pxc-2 2415:	Readiness probe failed: ERROR 2003 (HY000): Can't connect to MySQL server on '10.244.1.7:33062' (111)
+ [[ '' == \P\r\i\m\a\r\y ]]
+ exit 1

11:48:53 StatefulSet test-cluster-pxc 1759:	create Claim datadir-test-cluster-pxc-0 Pod test-cluster-pxc-0 in StatefulSet test-cluster-pxc success
11:48:53 StatefulSet test-cluster-pxc 1759:	create Pod test-cluster-pxc-0 in StatefulSet test-cluster-pxc successful
11:49:59 StatefulSet test-cluster-pxc 2049:	create Claim datadir-test-cluster-pxc-1 Pod test-cluster-pxc-1 in StatefulSet test-cluster-pxc success
11:49:59 StatefulSet test-cluster-pxc 2049:	create Pod test-cluster-pxc-1 in StatefulSet test-cluster-pxc successful
11:51:05 StatefulSet test-cluster-pxc 2370:	create Claim datadir-test-cluster-pxc-2 Pod test-cluster-pxc-2 in StatefulSet test-cluster-pxc success
11:51:05 StatefulSet test-cluster-pxc 2370:	create Pod test-cluster-pxc-2 in StatefulSet test-cluster-pxc successful
